# Series

In [857]:
import numpy as np
import pandas as pd

In [858]:
labels = ['a','b','c']
my_list = [10,20,30]
my_arr = np.array(my_list)
my_dict1 = {'a':10, 'b':20, 'c':30}

In [859]:
df0 = pd.Series(my_list)
df0

0    10
1    20
2    30
dtype: int64

In [860]:
df2 = pd.Series(my_arr)
df2

0    10
1    20
2    30
dtype: int32

In [861]:
df2 = pd.Series(data=my_list, index=labels)
df2

a    10
b    20
c    30
dtype: int64

In [862]:
df3 = pd.Series(my_dict1)
df3

a    10
b    20
c    30
dtype: int64

In [863]:
ser1 = pd.Series([1,2,3,4], index=['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [864]:
ser1['USA']

1

In [865]:
ser1[0]

1

In [866]:
ser2 = pd.Series([1,2,5,4], index=['USA','Germany','Italy','Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [867]:
ser2[['USA','Japan']]

USA      1
Japan    4
dtype: int64

In [868]:
ser2[[0,-1]]

USA      1
Japan    4
dtype: int64

In [869]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [870]:
ser1.shape

(4,)

# DataFrames

In [871]:
from numpy.random import randn
np.random.seed(101)

In [872]:
# rand_mat1 = randn(5)
# rand_mat1

In [873]:
# df = pd.DataFrame(rand_mat1)
# type(df)

In [874]:
rand_mat = randn(5, 4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [875]:
df = pd.DataFrame(rand_mat, index='A B C D E'.split(), columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Indexing (Grabbing)

### Columns Indexing

In [876]:
df1 = df["W"]
df1

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [877]:
type(df1)

pandas.core.series.Series

In [878]:
mylist1 = list(df1)
mylist1

[2.706849839399938,
 0.6511179479432686,
 -2.018168244037392,
 0.18869530944922425,
 0.19079432237171562]

In [879]:
myarr1 = np.array(df1)
myarr1.shape

(5,)

In [880]:
df2 = df["W Z".split()]
df2

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [881]:
type(df2)

pandas.core.frame.DataFrame

In [882]:
mylist2 = list(df2)
mylist2

['W', 'Z']

In [883]:
myarr2 = np.array(df2)
myarr2.shape

(5, 2)

### Row Indexing

In [884]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [885]:
type(df.loc['A'])

pandas.core.series.Series

In [886]:
df.loc['A'].shape

(4,)

In [887]:
list(df.loc['A'])

[2.706849839399938, 0.6281327087844596, 0.9079694464765431, 0.5038257538223936]

In [888]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

### 2D Slicing

In [889]:
df.loc['A B'.split(), 'Z W'.split()]

          Z         W
A  0.503826  2.706850
B  0.605965  0.651118

In [890]:
df.iloc[[0, 1],[-1, 0]]

          Z         W
A  0.503826  2.706850
B  0.605965  0.651118

In [891]:
df.iloc[[0, 1],0:3]

          W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

In [892]:
type(df.iloc[[0, 1],0:3])

pandas.core.frame.DataFrame

## Add Columns

In [893]:
ser3 = pd.Series({"A": 1, "B": 2, "C": 3, "D": 4, "F": 5})
ser3

A    1
B    2
C    3
D    4
F    5
dtype: int64

In [894]:
df['new'] = ser3
df

          W         X         Y         Z  new
A  2.706850  0.628133  0.907969  0.503826  1.0
B  0.651118 -0.319318 -0.848077  0.605965  2.0
C -2.018168  0.740122  0.528813 -0.589001  3.0
D  0.188695 -0.758872 -0.933237  0.955057  4.0
E  0.190794  1.978757  2.605967  0.683509  NaN

In [895]:
df

          W         X         Y         Z  new
A  2.706850  0.628133  0.907969  0.503826  1.0
B  0.651118 -0.319318 -0.848077  0.605965  2.0
C -2.018168  0.740122  0.528813 -0.589001  3.0
D  0.188695 -0.758872 -0.933237  0.955057  4.0
E  0.190794  1.978757  2.605967  0.683509  NaN

In [896]:
new_column = 'CA NY WY OR CO'.split()
df['States'] = new_column
df

          W         X         Y         Z  new States
A  2.706850  0.628133  0.907969  0.503826  1.0     CA
B  0.651118 -0.319318 -0.848077  0.605965  2.0     NY
C -2.018168  0.740122  0.528813 -0.589001  3.0     WY
D  0.188695 -0.758872 -0.933237  0.955057  4.0     OR
E  0.190794  1.978757  2.605967  0.683509  NaN     CO

## Remove Columns and Rows

In [897]:
# del df['new']
# df

In [898]:
df_nonnew = df.drop('new', axis=1)
df_nonnew

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [899]:
df.drop('A')

          W         X         Y         Z  new States
B  0.651118 -0.319318 -0.848077  0.605965  2.0     NY
C -2.018168  0.740122  0.528813 -0.589001  3.0     WY
D  0.188695 -0.758872 -0.933237  0.955057  4.0     OR
E  0.190794  1.978757  2.605967  0.683509  NaN     CO

In [900]:
df.drop('new States'.split(), axis=1, inplace = True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Condition

In [901]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [902]:
positive_df = df[df>0]
positive_df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [903]:
df[df[['W', 'Z']]>0]

          W   X   Y         Z
A  2.706850 NaN NaN  0.503826
B  0.651118 NaN NaN  0.605965
C       NaN NaN NaN       NaN
D  0.188695 NaN NaN  0.955057
E  0.190794 NaN NaN  0.683509

In [904]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [905]:
df.loc[:,'W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [906]:
df[df['W']>0]['Y'].loc['A']

0.9079694464765431

In [907]:
df[df['W']>0].loc['A','Y']

0.9079694464765431

In [908]:
df.loc[df['W']>0, 'Y'].loc['A']

0.9079694464765431

In [909]:
df[(df['W']>0) & (df['Y']>0)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [910]:
df.loc['A']>0

W    True
X    True
Y    True
Z    True
Name: A, dtype: bool

In [911]:
df.loc[df['W']>0,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
D  0.188695  0.955057
E  0.190794  0.683509

In [912]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [913]:
df.loc[:,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [914]:
df.loc[:,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [915]:
# df.loc[df.loc['B']>0, df['W']>0]

In [916]:
new_column = 'CA NY WY OR CO'.split()
df['States'] = new_column
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [917]:
df.reset_index(inplace=True)
df

  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

In [918]:
df.set_index('States', inplace=True)
df

       index         W         X         Y         Z
States
CA         A  2.706850  0.628133  0.907969  0.503826
NY         B  0.651118 -0.319318 -0.848077  0.605965
WY         C -2.018168  0.740122  0.528813 -0.589001
OR         D  0.188695 -0.758872 -0.933237  0.955057
CO         E  0.190794  1.978757  2.605967  0.683509

In [919]:
df.describe()

              W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [920]:
ser_w = df['W']>0
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

SyntaxError: invalid syntax (613600502.py, line 1)