# Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
my_arr = np.array(my_list)
my_dict1 = {'a':10, 'b':20, 'c':30}

In [3]:
df0 = pd.Series(my_list)
df0

0    10
1    20
2    30
dtype: int64

In [4]:
df2 = pd.Series(my_arr)
df2

0    10
1    20
2    30
dtype: int32

In [5]:
df2 = pd.Series(data=my_list, index=labels)
df2

a    10
b    20
c    30
dtype: int64

In [6]:
df3 = pd.Series(my_dict1)
df3

a    10
b    20
c    30
dtype: int64

In [7]:
ser1 = pd.Series([1,2,3,4], index=['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [8]:
ser1['USA']

1

In [9]:
ser1[0]

1

In [10]:
ser2 = pd.Series([1,2,5,4], index=['USA','Germany','Italy','Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [11]:
ser2[['USA','Japan']]

USA      1
Japan    4
dtype: int64

In [12]:
ser2[[0,-1]]

USA      1
Japan    4
dtype: int64

In [13]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [14]:
ser1.shape

(4,)

# DataFrames

In [15]:
from numpy.random import randn
np.random.seed(101)

In [16]:
# rand_mat1 = randn(5)
# rand_mat1

In [17]:
# df = pd.DataFrame(rand_mat1)
# type(df)

In [18]:
rand_mat = randn(5, 4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [19]:
df = pd.DataFrame(rand_mat, index='A B C D E'.split(), columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Indexing (Grabbing)

### Columns Indexing

In [20]:
df1 = df["W"]
df1

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
type(df1)

pandas.core.series.Series

In [22]:
mylist1 = list(df1)
mylist1

[2.706849839399938,
 0.6511179479432686,
 -2.018168244037392,
 0.18869530944922425,
 0.19079432237171562]

In [23]:
myarr1 = np.array(df1)
myarr1.shape

(5,)

In [24]:
df2 = df["W Z".split()]
df2

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [25]:
type(df2)

pandas.core.frame.DataFrame

In [26]:
mylist2 = list(df2)
mylist2

['W', 'Z']

In [27]:
myarr2 = np.array(df2)
myarr2.shape

(5, 2)

### Row Indexing

In [28]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [29]:
type(df.loc['A'])

pandas.core.series.Series

In [30]:
df.loc['A'].shape

(4,)

In [31]:
list(df.loc['A'])

[2.706849839399938, 0.6281327087844596, 0.9079694464765431, 0.5038257538223936]

In [32]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

### 2D Slicing

In [33]:
df.loc['A B'.split(), 'Z W'.split()]

          Z         W
A  0.503826  2.706850
B  0.605965  0.651118

In [34]:
df.iloc[[0, 1],[-1, 0]]

          Z         W
A  0.503826  2.706850
B  0.605965  0.651118

In [35]:
df.iloc[[0, 1],0:3]

          W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

In [36]:
type(df.iloc[[0, 1],0:3])

pandas.core.frame.DataFrame

## Add Columns

In [37]:
ser3 = pd.Series({"A": 1, "B": 2, "C": 3, "D": 4, "F": 5})
ser3

A    1
B    2
C    3
D    4
F    5
dtype: int64

In [38]:
df['new'] = ser3
df

          W         X         Y         Z  new
A  2.706850  0.628133  0.907969  0.503826  1.0
B  0.651118 -0.319318 -0.848077  0.605965  2.0
C -2.018168  0.740122  0.528813 -0.589001  3.0
D  0.188695 -0.758872 -0.933237  0.955057  4.0
E  0.190794  1.978757  2.605967  0.683509  NaN

In [39]:
df

          W         X         Y         Z  new
A  2.706850  0.628133  0.907969  0.503826  1.0
B  0.651118 -0.319318 -0.848077  0.605965  2.0
C -2.018168  0.740122  0.528813 -0.589001  3.0
D  0.188695 -0.758872 -0.933237  0.955057  4.0
E  0.190794  1.978757  2.605967  0.683509  NaN

In [40]:
new_column = 'CA NY WY OR CO'.split()
df['States'] = new_column
df

          W         X         Y         Z  new States
A  2.706850  0.628133  0.907969  0.503826  1.0     CA
B  0.651118 -0.319318 -0.848077  0.605965  2.0     NY
C -2.018168  0.740122  0.528813 -0.589001  3.0     WY
D  0.188695 -0.758872 -0.933237  0.955057  4.0     OR
E  0.190794  1.978757  2.605967  0.683509  NaN     CO

## Add Rows

In [41]:
df0 = df.copy()
df0.loc['F'] = pd.Series([1,2,3,4,5, 'FF'], index=["W","Y","X","Z","new","States"])
df0

          W         X         Y         Z  new States
A  2.706850  0.628133  0.907969  0.503826  1.0     CA
B  0.651118 -0.319318 -0.848077  0.605965  2.0     NY
C -2.018168  0.740122  0.528813 -0.589001  3.0     WY
D  0.188695 -0.758872 -0.933237  0.955057  4.0     OR
E  0.190794  1.978757  2.605967  0.683509  NaN     CO
F  1.000000  3.000000  2.000000  4.000000  5.0     FF

In [42]:
dfg = pd.DataFrame([[12,42,13,46,15, 'FF']], index=['G'], columns=["W","X","Y","Z","new","States"])
df0 = pd.concat([df0, dfg])
df0

           W          X          Y          Z   new States
A   2.706850   0.628133   0.907969   0.503826   1.0     CA
B   0.651118  -0.319318  -0.848077   0.605965   2.0     NY
C  -2.018168   0.740122   0.528813  -0.589001   3.0     WY
D   0.188695  -0.758872  -0.933237   0.955057   4.0     OR
E   0.190794   1.978757   2.605967   0.683509   NaN     CO
F   1.000000   3.000000   2.000000   4.000000   5.0     FF
G  12.000000  42.000000  13.000000  46.000000  15.0     FF

In [43]:
a = pd.Series([1,2,3,4,5, 'FF'], index=["W","X","Y","Z","new","States"])
b = pd.Series([1,2,3,4,5, 'FF'], index=["W","X","Y","Z","new","States"])
c = pd.concat([a,b],axis = 1)
c

         0   1
W        1   1
X        2   2
Y        3   3
Z        4   4
new      5   5
States  FF  FF

In [44]:
c.T

   W  X  Y  Z new States
0  1  2  3  4   5     FF
1  1  2  3  4   5     FF

In [45]:
d = pd.Series([1,2], index = [0,1])
d.T

0    1
1    2
dtype: int64

In [46]:
c = pd.concat([c.T,d.T], axis=1)
c

   W  X  Y  Z new States  0
0  1  2  3  4   5     FF  1
1  1  2  3  4   5     FF  2

In [47]:

c = pd.concat([c,b],axis = 1)
c

          W    X    Y    Z  new States    0    0
0         1    2    3    4    5     FF  1.0  NaN
1         1    2    3    4    5     FF  2.0  NaN
States  NaN  NaN  NaN  NaN  NaN    NaN  NaN   FF
W       NaN  NaN  NaN  NaN  NaN    NaN  NaN    1
X       NaN  NaN  NaN  NaN  NaN    NaN  NaN    2
Y       NaN  NaN  NaN  NaN  NaN    NaN  NaN    3
Z       NaN  NaN  NaN  NaN  NaN    NaN  NaN    4
new     NaN  NaN  NaN  NaN  NaN    NaN  NaN    5

In [48]:

c = c.T
c

          0    1 States    W    X    Y    Z  new
W         1    1    NaN  NaN  NaN  NaN  NaN  NaN
X         2    2    NaN  NaN  NaN  NaN  NaN  NaN
Y         3    3    NaN  NaN  NaN  NaN  NaN  NaN
Z         4    4    NaN  NaN  NaN  NaN  NaN  NaN
new       5    5    NaN  NaN  NaN  NaN  NaN  NaN
States   FF   FF    NaN  NaN  NaN  NaN  NaN  NaN
0       1.0  2.0    NaN  NaN  NaN  NaN  NaN  NaN
0       NaN  NaN     FF    1    2    3    4    5

## Remove Columns and Rows

In [49]:
# del df['new']
# df

In [50]:
df_nonnew = df.drop('new', axis=1)
df_nonnew

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [51]:
df.drop('A')

          W         X         Y         Z  new States
B  0.651118 -0.319318 -0.848077  0.605965  2.0     NY
C -2.018168  0.740122  0.528813 -0.589001  3.0     WY
D  0.188695 -0.758872 -0.933237  0.955057  4.0     OR
E  0.190794  1.978757  2.605967  0.683509  NaN     CO

In [52]:
df.drop('new States'.split(), axis=1, inplace = True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Condition

In [53]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [54]:
positive_df = df[df>0]
positive_df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df[df[['W', 'Z']]>0]

          W   X   Y         Z
A  2.706850 NaN NaN  0.503826
B  0.651118 NaN NaN  0.605965
C       NaN NaN NaN       NaN
D  0.188695 NaN NaN  0.955057
E  0.190794 NaN NaN  0.683509

In [56]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df.loc[:,'W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [58]:
df[df['W']>0]['Y'].loc['A']

0.9079694464765431

In [59]:
df[df['W']>0].loc['A','Y']

0.9079694464765431

In [60]:
df.loc[df['W']>0, 'Y'].loc['A']

0.9079694464765431

In [61]:
df[(df['W']>0) & (df['Y']>0)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [62]:
df.loc['A']>0

W    True
X    True
Y    True
Z    True
Name: A, dtype: bool

In [63]:
df.loc[df['W']>0,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
D  0.188695  0.955057
E  0.190794  0.683509

In [64]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
df.loc[:,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [66]:
df.loc[:,df.loc['B']>0]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [67]:
# df.loc[df.loc['B']>0, df['W']>0]

In [68]:
new_column = 'CA NY WY OR CO'.split()
df['States'] = new_column
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [69]:
df.reset_index(inplace=True)
df

  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

In [70]:
df.set_index('States', inplace=True)
df

       index         W         X         Y         Z
States
CA         A  2.706850  0.628133  0.907969  0.503826
NY         B  0.651118 -0.319318 -0.848077  0.605965
WY         C -2.018168  0.740122  0.528813 -0.589001
OR         D  0.188695 -0.758872 -0.933237  0.955057
CO         E  0.190794  1.978757  2.605967  0.683509

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   5 non-null      object
 1   W       5 non-null      float64
 2   X       5 non-null      float64
 3   Y       5 non-null      float64
 4   Z       5 non-null      float64
dtypes: float64(4), object(1)
memory usage: 240.0+ bytes

In [72]:
df.dtypes

index     object
W        float64
X        float64
Y        float64
Z        float64
dtype: object

In [73]:
df.describe()

              W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [74]:
ser_w = df['W']>0
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

# Operation

In [75]:
df2 = pd.DataFrame({'col1':[1,2,666,4],'col2':[444.,555,666,444],'col3':'abc def ghi xyz'.split()})
df2

   col1   col2 col3
0     1  444.0  abc
1     2  555.0  def
2   666  666.0  ghi
3     4  444.0  xyz

In [76]:
df2['col2'].unique()

array([444., 555., 666.])

In [77]:
type(df2.loc[2].unique())

numpy.ndarray

In [78]:
type(df2['col2'].value_counts())

pandas.core.series.Series

In [79]:
import numpy as np


def func1(number):
    print(type(number))
    if type(number)!=str:
        return number*2 + 9
    else:
        return np.NaN

In [80]:
type(df2['col2'].apply(func1))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

pandas.core.series.Series

In [81]:
df2.iloc[0].apply(func1)

<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'str'>

col1     11.0
col2    897.0
col3      NaN
Name: 0, dtype: float64

In [82]:
df2.sort_values('col2')

   col1   col2 col3
0     1  444.0  abc
3     4  444.0  xyz
1     2  555.0  def
2   666  666.0  ghi

In [83]:
df2

   col1   col2 col3
0     1  444.0  abc
1     2  555.0  def
2   666  666.0  ghi
3     4  444.0  xyz

In [84]:
df2.sort_values('col2', inplace=True)
df2

   col1   col2 col3
0     1  444.0  abc
3     4  444.0  xyz
1     2  555.0  def
2   666  666.0  ghi

In [85]:
df2.loc[2]

col1      666
col2    666.0
col3      ghi
Name: 2, dtype: object

In [86]:
df2.reset_index()

   index  col1   col2 col3
0      0     1  444.0  abc
1      3     4  444.0  xyz
2      1     2  555.0  def
3      2   666  666.0  ghi

In [87]:
df2.loc[2]

col1      666
col2    666.0
col3      ghi
Name: 2, dtype: object

# I/O

## CSV
Comma Separated Values files are text files that use commas as field delimeters.<br>
Unless you're running the virtual environment included with the course, you may need to install <tt>xlrd</tt> and <tt>openpyxl</tt>.<br>
In your terminal/command prompt run:

    conda install xlrd
    conda install openpyxl

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

### CSV Input

In [88]:
Doc1 = pd.read_csv('example.csv')
Doc1

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [96]:
Doc2 = pd.read_excel('Excel_Sample.xlsx', index_col=0, sheet_name = 'Sheet2')
Doc2

        a     b  Unnamed: 3     d
A     0.0   1.0         NaN   3.0
B     4.0   5.0         NaN   7.0
C     8.0   9.0         NaN  11.0
NaN   NaN   NaN         NaN   NaN
NaN  12.0  13.0         NaN  15.0

In [90]:
pwd

'l:\\0-Processing\\2-PyTorch\\PyTorch\\Jose Portilla'

In [91]:
Doc01 = Doc1['a b c'.split()].set_index('a')
Doc01.to_csv('example_output (index=False_The a column is GONE).csv', index=False)
Doc01.to_csv('example_output (index=True_The a column is PRESERVED).csv', index=True)

    conda install lxml
    conda install html5lib
    conda install beautifulsoup4

In [97]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')
df

In [107]:
banklist = df[0]
banklist.head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

In [108]:
banklist.columns

Index(['Bank Name', 'City', 'State', 'Cert', 'Acquiring Institution',
       'Closing Date', 'Fund  Sort ascending'],
      dtype='object')

In [109]:
banklist.index

RangeIndex(start=0, stop=25, step=1)

In [117]:
# df[0].to_csv('Banklist.csv',index = False)
banklist.to_csv('Banklist.csv',index = False)
banklist.to_excel('Banklist.xlsx',index = False, sheet_name = 'Banks')

In [112]:
pwd

'l:\\0-Processing\\2-PyTorch\\PyTorch\\Jose Portilla'

# Different .apply .map and .applymap

## Source - https://stackoverflow.com/a/19798528
## Posted by jeremiahbuddha, modified by community. See post 'Timeline' for change history
## Retrieved 2026-08-26, License - CC BY-SA 4.0

In [118]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [119]:
f = lambda x: x.max() - x.min()

frame.apply(f)

b    1.461785
d    1.828564
e    2.513792
dtype: float64

In [120]:
format = lambda x: '%.2f' % x
frame.applymap(format)

            b      d      e
Utah     0.30   1.69  -1.71
Ohio    -1.16  -0.13   0.39
Texas    0.17   0.18   0.81
Oregon   0.07   0.64   0.33

In [125]:
frame['e'].map(format)

Utah      -1.71
Ohio       0.39
Texas      0.81
Oregon     0.33
Name: e, dtype: object